{% set version = "0.3-6" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-assertive
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/assertive_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/assertive/assertive_{{ version }}.tar.gz
  sha256: c403169e83c433b65e911f7fd640b378e2a4a4765a36063584b8458168a4ea0a

build:
  noarch: generic
  number: 3
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-assertive.base >=0.0_4
    - r-assertive.code
    - r-assertive.data
    - r-assertive.data.uk
    - r-assertive.data.us
    - r-assertive.datetimes
    - r-assertive.files
    - r-assertive.matrices
    - r-assertive.models
    - r-assertive.numbers
    - r-assertive.properties >=0.0_2
    - r-assertive.reflection >=0.0_2
    - r-assertive.sets >=0.0_2
    - r-assertive.strings
    - r-assertive.types >=0.0_2
    - r-knitr
  run:
    - r-base
    - r-assertive.base >=0.0_4
    - r-assertive.code
    - r-assertive.data
    - r-assertive.data.uk
    - r-assertive.data.us
    - r-assertive.datetimes
    - r-assertive.files
    - r-assertive.matrices
    - r-assertive.models
    - r-assertive.numbers
    - r-assertive.properties >=0.0_2
    - r-assertive.reflection >=0.0_2
    - r-assertive.sets >=0.0_2
    - r-assertive.strings
    - r-assertive.types >=0.0_2
    - r-knitr

test:
  commands:
    - $R -e "library('assertive')"           # [not win]
    - "\"%R%\" -e \"library('assertive')\""  # [win]

about:
  home: https://bitbucket.org/richierocks/assertive
  license: GPL-3.0-or-later
  summary: Lots of predicates (is_* functions) to check the state of your variables, and assertions (assert_* functions) to throw errors if they aren't in the right form.
  license_family: GPL3
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - jenzopr
